'use client';

import { useState, useEffect } from 'react';
import { SidebarDemo } from "@/components/ui/code.demo";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  User, 
  Mail, 
  Phone, 
  Building, 
  MapPin, 
  Globe,
  Camera,
  Loader2,
  Lock,
  Eye,
  EyeOff
} from 'lucide-react';
import { toast } from "sonner";
import { supabase } from '@/lib/supabase';
import { useSession } from 'next-auth/react';

interface UserProfile {
  id?: string;  // Make id optional since it will be generated by Supabase
  user_id: string;
  name: string;
  email: string;
  phone: string;
  company: string;
  role: string;
  address: string;
  city: string;
  country: string;
  website: string;
  avatarUrl?: string;
}

export default function ProfilePage() {
  const { data: session } = useSession();
  const [profile, setProfile] = useState<UserProfile>({
    user_id: '',
    name: '',
    email: '',
    phone: '',
    company: '',
    role: 'User',
    address: '',
    city: '',
    country: '',
    website: ''
  });
  const [isEditing, setIsEditing] = useState(false);
  const [editedProfile, setEditedProfile] = useState<UserProfile>(profile);
  const [isSaving, setIsSaving] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [isSavingAll, setIsSavingAll] = useState(false);

  useEffect(() => {
    if (session?.user?.id) {
      fetchProfile();
    }
  }, [session]);

  const fetchProfile = async () => {
    if (!session?.user?.id) {
      console.error('No user session found for profile');
      toast.error('User authentication required');
      return;
    }

    try {
      console.log('Fetching profile for user:', session.user.id);
      // Fetch profile from Supabase
      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('user_id', session.user.id)
        .single();

      console.log('Fetch result:', { data, error });

      if (error) {
        if (error.code === 'PGRST116') {
          console.log('No profile exists, creating default...');
          // No profile exists yet, create one with default values
          const { data: newProfile, error: createError } = await supabase
            .from('profiles')
            .insert([{
              user_id: session.user.id,
              name: session.user.name || '',
              email: session.user.email || '',
              phone: '',
              company: '',
              role: 'User',
              address: '',
              city: '',
              country: '',
              website: '',
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString()
            }])
            .select()
            .single();

          console.log('Create result:', { newProfile, createError });

          if (createError) {
            console.error('Error creating profile:', createError);
            throw createError;
          }
          if (newProfile) {
            setProfile(newProfile);
            setEditedProfile(newProfile);
            
            // Also update the auth metadata if needed
            const { error: updateError } = await supabase.auth.updateUser({
              data: {
                name: session.user.name,
                email: session.user.email
              }
            });
            
            if (updateError) {
              console.error('Error updating auth metadata:', updateError);
            }
          }
          return;
        }
        throw error;
      }

      if (data) {
        setProfile(data);
        setEditedProfile(data);
      }
    } catch (error) {
      console.error('Error fetching profile:', error);
      toast.error('Failed to fetch profile');
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    console.log('Input changed:', { name, value });
    setEditedProfile(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSave = async () => {
    if (!session?.user?.id) {
      console.error('No user session found for saving profile');
      toast.error('User authentication required');
      return;
    }

    console.log('Starting save process...', { editedProfile, isEditing });
    setIsSaving(true);
    try {
      // First check if profile exists
      const { data: existingProfile, error: checkError } = await supabase
        .from('profiles')
        .select('*')
        .eq('user_id', session.user.id)
        .single();

      console.log('Check existing profile:', { existingProfile, checkError });

      if (checkError && checkError.code === 'PGRST116') {
        // Profile doesn't exist, create it
        console.log('Profile does not exist, creating...');
        const { data: newProfile, error: createError } = await supabase
          .from('profiles')
          .insert([{
            user_id: session.user.id,
            name: editedProfile.name,
            email: editedProfile.email,
            phone: editedProfile.phone,
            company: editedProfile.company,
            role: editedProfile.role,
            address: editedProfile.address,
            city: editedProfile.city,
            country: editedProfile.country,
            website: editedProfile.website
          }])
          .select()
          .single();

        console.log('Create result:', { newProfile, createError });

        if (createError) throw createError;
        if (newProfile) {
          setProfile(newProfile);
          setEditedProfile(newProfile);
        }
      } else {
        // Profile exists, update it
        console.log('Profile exists, updating...', existingProfile.id);
        const { error: updateError } = await supabase
          .from('profiles')
          .update({
            name: editedProfile.name,
            email: editedProfile.email,
            phone: editedProfile.phone,
            company: editedProfile.company,
            role: editedProfile.role,
            address: editedProfile.address,
            city: editedProfile.city,
            country: editedProfile.country,
            website: editedProfile.website
          })
          .eq('id', existingProfile.id)
          .eq('user_id', session.user.id);

        console.log('Update result:', { updateError });

        if (updateError) throw updateError;
        setProfile({ ...editedProfile, id: existingProfile.id });
      }

      setIsEditing(false);
      toast.success('Profile updated successfully');
    } catch (error) {
      console.error('Error updating profile:', error);
      toast.error('Failed to update profile');
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => {
    setEditedProfile(profile);
    setIsEditing(false);
  };

  const handleAvatarUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!session?.user?.id) {
      console.error('No user session found for avatar upload');
      toast.error('User authentication required');
      return;
    }

    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    try {
      // Upload to Supabase Storage
      const fileExt = file.name.split('.').pop();
      const fileName = `${session.user.id}-avatar.${fileExt}`;
      const { error: uploadError, data } = await supabase.storage
        .from('avatars')
        .upload(fileName, file, { upsert: true });

      if (uploadError) throw uploadError;

      // Get public URL
      const { data: { publicUrl } } = supabase.storage
        .from('avatars')
        .getPublicUrl(fileName);

      // Update profile with new avatar URL
      const { error: updateError } = await supabase
        .from('profiles')
        .update({ avatarUrl: publicUrl })
        .eq('user_id', session.user.id);

      if (updateError) throw updateError;

      setProfile(prev => ({ ...prev, avatarUrl: publicUrl }));
      toast.success('Avatar uploaded successfully');
    } catch (error) {
      console.error('Error uploading avatar:', error);
      toast.error('Failed to upload avatar');
    } finally {
      setIsUploading(false);
    }
  };

  const handleSaveAll = async () => {
    if (!session?.user?.id) {
      console.error('No user session found for saving all profile data');
      toast.error('User authentication required');
      return;
    }
    
    setIsSavingAll(true);
    try {
      // Use the same save logic as handleSave
      await handleSave();
    } finally {
      setIsSavingAll(false);
    }
  };

  return (
    <SidebarDemo>
      <div className="p-6 space-y-6">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <h1 className="text-2xl font-semibold text-white">Profile</h1>
            <p className="text-sm text-neutral-400">
              Manage your personal information and preferences
            </p>
          </div>
          {!isEditing ? (
            <div className="flex items-center gap-2">
              <Button
                onClick={() => {
                  setIsEditing(true);
                  setEditedProfile(profile);
                }}
                variant="outline"
                className="flex items-center gap-2"
              >
                Edit Profile
              </Button>
            </div>
          ) : (
            <div className="flex items-center gap-2">
              <Button
                onClick={() => {
                  handleSave();
                }}
                variant="outline"
                className="flex items-center gap-2"
              >
                Cancel
              </Button>
              <Button
                onClick={() => {
                  handleSave();
                }}
                disabled={isSaving}
                className="flex items-center gap-2"
              >
                {isSaving ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Saving...
                  </>
                ) : (
                  'Save Changes'
                )}
              </Button>
              <Button
                onClick={() => {
                  handleSaveAll();
                }}
                disabled={isSavingAll}
                className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700"
              >
                {isSavingAll ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Saving All...
                  </>
                ) : (
                  'Save All'
                )}
              </Button>
            </div>
          )}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Avatar Card */}
          <Card className="bg-neutral-800 border-neutral-700 p-6 lg:col-span-1">
            <div className="flex flex-col items-center space-y-4">
              <div className="relative">
                <div className="h-32 w-32 rounded-full bg-neutral-700 flex items-center justify-center overflow-hidden">
                  {profile.avatarUrl ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={profile.avatarUrl}
                      alt={profile.name}
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <User className="h-16 w-16 text-neutral-500" />
                  )}
                </div>
                {isEditing && (
                  <label
                    htmlFor="avatar-upload"
                    className="absolute bottom-0 right-0 p-2 bg-neutral-900 rounded-full cursor-pointer hover:bg-neutral-700 transition-colors"
                  >
                    {isUploading ? (
                      <Loader2 className="h-4 w-4 animate-spin text-neutral-400" />
                    ) : (
                      <Camera className="h-4 w-4 text-neutral-400" />
                    )}
                    <input
                      id="avatar-upload"
                      type="file"
                      accept="image/*"
                      className="hidden"
                      onChange={handleAvatarUpload}
                      disabled={isUploading}
                    />
                  </label>
                )}
              </div>
              <div className="text-center">
                <h2 className="text-xl font-semibold text-white">{profile.name}</h2>
                <p className="text-sm text-neutral-400">{profile.role}</p>
              </div>
            </div>
          </Card>

          {/* Details Card */}
          <Card className="bg-neutral-800 border-neutral-700 p-6 lg:col-span-2">
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Personal Information */}
                <div className="space-y-4">
                  <h3 className="text-lg font-medium text-white">Personal Information</h3>
                  
                  <div className="space-y-2">
                    <label className="text-sm text-neutral-400">Full Name</label>
                    <div className="flex items-center gap-2">
                      <User className="h-4 w-4 text-neutral-500" />
                      {isEditing ? (
                        <input
                          type="text"
                          name="name"
                          value={editedProfile.name}
                          onChange={handleInputChange}
                          className="w-full px-3 py-2 bg-neutral-900 border border-neutral-700 rounded-md text-white"
                        />
                      ) : (
                        <span className="text-white">{profile.name}</span>
                      )}
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-sm text-neutral-400">Email</label>
                    <div className="flex items-center gap-2">
                      <Mail className="h-4 w-4 text-neutral-500" />
                      {isEditing ? (
                        <input
                          type="email"
                          name="email"
                          value={editedProfile.email}
                          onChange={handleInputChange}
                          className="w-full px-3 py-2 bg-neutral-900 border border-neutral-700 rounded-md text-white"
                        />
                      ) : (
                        <span className="text-white">{profile.email}</span>
                      )}
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-sm text-neutral-400">Phone</label>
                    <div className="flex items-center gap-2">
                      <Phone className="h-4 w-4 text-neutral-500" />
                      {isEditing ? (
                        <input
                          type="tel"
                          name="phone"
                          value={editedProfile.phone}
                          onChange={handleInputChange}
                          className="w-full px-3 py-2 bg-neutral-900 border border-neutral-700 rounded-md text-white"
                        />
                      ) : (
                        <span className="text-white">{profile.phone}</span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Company Information */}
                <div className="space-y-4">
                  <h3 className="text-lg font-medium text-white">Company Information</h3>
                  
                  <div className="space-y-2">
                    <label className="text-sm text-neutral-400">Company</label>
                    <div className="flex items-center gap-2">
                      <Building className="h-4 w-4 text-neutral-500" />
                      {isEditing ? (
                        <input
                          type="text"
                          name="company"
                          value={editedProfile.company}
                          onChange={handleInputChange}
                          className="w-full px-3 py-2 bg-neutral-900 border border-neutral-700 rounded-md text-white"
                        />
                      ) : (
                        <span className="text-white">{profile.company}</span>
                      )}
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-sm text-neutral-400">Address</label>
                    <div className="flex items-center gap-2">
                      <MapPin className="h-4 w-4 text-neutral-500" />
                      {isEditing ? (
                        <input
                          type="text"
                          name="address"
                          value={editedProfile.address}
                          onChange={handleInputChange}
                          className="w-full px-3 py-2 bg-neutral-900 border border-neutral-700 rounded-md text-white"
                        />
                      ) : (
                        <span className="text-white">{profile.address}</span>
                      )}
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-sm text-neutral-400">Website</label>
                    <div className="flex items-center gap-2">
                      <Globe className="h-4 w-4 text-neutral-500" />
                      {isEditing ? (
                        <input
                          type="text"
                          name="website"
                          value={editedProfile.website}
                          onChange={handleInputChange}
                          className="w-full px-3 py-2 bg-neutral-900 border border-neutral-700 rounded-md text-white"
                        />
                      ) : (
                        <span className="text-white">{profile.website}</span>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </SidebarDemo>
  );
} 